export const MCMASTER_LETTER_GRADES = [
  { letter: "A+", min: 90 },
  { letter: "A", min: 85 },
  { letter: "A-", min: 80 },
  { letter: "B+", min: 77 },
  { letter: "B", min: 73 },
  { letter: "B-", min: 70 },
  { letter: "C+", min: 67 },
  { letter: "C", min: 63 },
  { letter: "C-", min: 60 },
  { letter: "D+", min: 57 },
  { letter: "D", min: 53 },
  { letter: "D-", min: 50 },
  { letter: "F", min: 0 },
];
